name: Auto-merge PRs

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: actions/github-script@v7
        with:
          script: |
            const pull_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            try {
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number,
                merge_method: 'squash'
              });
              core.info(`Pull request #${pull_number} merged into main.`);
            } catch (error) {
              core.setFailed(`Failed to merge pull request: ${error.message}`);
            }
